name 'nibalizer-puppetboard'
version '1.0.0'
source 'git://github.com/nibalizer/puppet-module-puppetboard.git'
author 'Spencer Krum'
description 'Install and configure PuppetBoard'
summary 'Install and configure PuppetBoard'
license 'ASL 2.0'
project_page 'https://github.com/nibalizer/puppet-module-puppetboard'

dependency 'puppetlabs/stdlib'
dependency 'nibalizer/python', '>= 1.1.4'
dependency 'puppetlabs/vcsrepo', '>= 0.1.2'
dependency 'puppetlabs/apache', '>=0.9.0'
