name 'nibalizer-puppetboard'
version '2.5.0'
source 'git://github.com/nibalizer/puppet-module-puppetboard.git'
author 'Spencer Krum'
description 'Install and configure PuppetBoard'
summary 'Install and configure PuppetBoard'
license 'ASL 2.0'
project_page 'https://github.com/nibalizer/puppet-module-puppetboard'

dependency 'puppetlabs/stdlib', '>= 3.0.0'
dependency 'stankevich/python', '>= 1.1.4'
dependency 'puppetlabs/vcsrepo', '>= 0.1.2'
